### ISSUE TITLE
Add custom className to the anchor element

### ISSUE THREAD

**Issue by vntw** [One-com/react-show-more#1]
Hi,

would you accept a PR that adds the ability to add a class to the anchor elements for easier styling?

Thanks!

**Comment by pablosichert** [comment]
Yes, sure - just submit it as a pull request to this repo :sun_with_face:

**Comment by asogani1** [comment]
why only anchor elements? can't we add class to customise other html elements?
write now it is adding className after more is clicked else it us just wrapping it to span and no class added.
