### ISSUE TITLE
Configuration doc for more/less is misleading

### ISSUE THREAD

**Issue by vntw** [One-com/react-show-more#3]
Just spotted this after implementing the anchorClass:

The default values for `more`/`less` show `…` to be the default value. But in fact I can't change this, since the component will always render `<span>... <a href='#' className={anchorClass} onClick={this.toggleLines}>`, no matter what I configure.

This was a bit misleading, at least for me. I guess the description should make it clear that you can only configure what's inside the anchor element.

WDYT?

**Comment by pablosichert** [comment]
Oh, good catch - this mistake in the documentation comes from copying over the docs from [react-truncate](https://github.com/One-com/react-truncate).

It always renders the dots, but the text displayed next to it comes from [`{more}`](https://github.com/One-com/react-show-more/blob/master/src/ShowMore.js#L57)
