### ISSUE TITLE
"Warning: Failed prop type: The prop `children` is marked as required in `ShowMore`, but its value is `undefined`."

### ISSUE THREAD

**Issue by LanderN** [One-com/react-show-more#5]
I don't think children should be a necessary prop, since we define the children inside the tag.

**Comment by pablosichert** [comment]
I guess you have a point there :sun_with_face:
Technically the module works without passing children, even though that would not make much sense.

**Comment by pablosichert** [comment]
Out with [`v1.1.1`](https://github.com/One-com/react-show-more/releases/tag/v1.1.1) on npm
